### ISSUE TITLE
Create Register UI

### ISSUE THREAD

**Issue by maszhar** [maszhar/ngitung-duit-android#1]
# Backlog

Related to backlog maszhar/ngitung-duit#1 

# TODO

- [x] Add text input elements for firstname, lastname, email, password, password confirmation
- [x] Add checkbox for agreement check to the terms of service
- [x] Add button for submit the registration
